query ($projectFullPath: ID!, $branchName: String) {
    project(fullPath: $projectFullPath) {
        id
        name
        path
        fullPath
        repository {
            tree(recursive: true, ref: $branchName) {
                lastCommit {
                    title
                    authoredDate
                    authorName
                }
            }
        }
    }
}
