query ($projectFullPath: ID!) {
    project(fullPath: $projectFullPath) {
        id
        name
        path
        fullPath

        repository {
            branchNames(limit: 100, searchPattern: "*", offset: 0)
        }

        pipelineSchedules {
            edges {
                node {
                    id
                    description
                    active
                    nextRunAt

                    owner {
                        id
                        username
                        publicEmail
                        state
                    }
                }
            }
        }
    }
}
